services:
    Demo\Bundle\ShoppingListButtonsBundle\EventListener\CheckoutShoppingListStartConditionListener:
        tags:
            - { name: kernel.event_listener, event: extendable_condition.shopping_list_start, method: onShoppingListStart }
