parameters:
    demo_shipping_table_rates.integration.channel.type: 'shipping_table_rates'
    demo_shipping_table_rates.integration.transport.type: 'shipping_table_rates'
    demo_shipping_table_rates.entity.shipping_table_rate.class: 'Demo\Bundle\ShippingTableRatesBundle\Entity\ShippingTableRate'

services:
    demo_shipping_table_rates.provider.channel:
        class: 'Demo\Bundle\ShippingTableRatesBundle\Provider\ShippingTableRatesChannelType'
        tags:
            - { name: oro_integration.channel, type: '%demo_shipping_table_rates.integration.channel.type%'}

    demo_shipping_table_rates.provider.transport:
        class: 'Demo\Bundle\ShippingTableRatesBundle\Provider\ShippingTableRatesTransport'
        tags:
            - { name: oro_integration.transport, type: '%demo_shipping_table_rates.integration.transport.type%', channel_type: '%demo_shipping_table_rates.integration.channel.type%' }

    demo_shipping_table_rates.method.identifier_generator.method:
        parent: oro_integration.generator.prefixed_identifier_generator
        public: false
        arguments:
            - '%demo_shipping_table_rates.integration.channel.type%'

    demo_shipping_table_rates.provider.price:
        class: 'Demo\Bundle\ShippingTableRatesBundle\Provider\ShippingTableRatesPriceProvider'
        public: false
        arguments:
            - '@oro_entity.doctrine_helper'

    demo_shipping_table_rates.factory.method:
        class: 'Demo\Bundle\ShippingTableRatesBundle\Factory\ShippingTableRatesMethodFactory'
        public: false
        arguments:
            - '@demo_shipping_table_rates.method.identifier_generator.method'
            - '@oro_locale.helper.localization'
            - '@demo_shipping_table_rates.provider.price'

    demo_shipping_table_rates.method.provider:
        class: 'Oro\Bundle\ShippingBundle\Method\Provider\Integration\ChannelShippingMethodProvider'
        arguments:
            - '%demo_shipping_table_rates.integration.channel.type%'
            - '@oro_entity.doctrine_helper'
            - '@demo_shipping_table_rates.factory.method'
        tags:
            - { name: oro_shipping_method_provider }
            - { name: doctrine.orm.entity_listener, entity: 'Oro\Bundle\IntegrationBundle\Entity\Channel', event: postLoad }
