layout:
    actions:
        - '@setOption':
            id: __products
            optionName: items_data.productPrices
            optionValue: '=data["frontend_product_prices_cached"].getByProducts(items)'
